config/routes.rb
Rails.application.routes.draw do
  root 'notes#index'
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def to_turbo_frame_id
    "#{self.class.name.underscore}_#{new_record? ? 'new' : id}"
  end
end

app/models/note.rb
class Note < ApplicationRecord
  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[edit update destroy]

  def index
    @notes = Note.all
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to notes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to notes_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.min.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag "application" %>

    <%= stimulus_include_tags %>
    <%= javascript_include_tag "turbo", type: "module-shim" %>
    <%= yield :head %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with model: note, url: note.new_record? ? notes_path : note_path(note) do |f| %>
  <% if note.errors.any? %>
    <%= note.errors.full_messages.join(', ') %>
  <% end %>
  <%= f.text_field :text, autocomplete: :off %>
  <%= f.submit note.new_record? ? 'Add' : 'Save' %>
<% end %>

app/views/notes/_note.html.erb
<li>
  <%= turbo_frame_tag note.to_turbo_frame_id do %>
    <div data-controller='note'>
      <%= link_to note.text, edit_note_path(note), data: { 'note-target': 'text' } %>
      <%= button_to 'Remove', note_path(note), method: :delete, form: { data: { 'turbo-frame': '_top' } } %>
    </div>
  <% end %>
</li>
<br>

app/views/notes/edit.html.erb
<h2>Edit note</h2>

<%= turbo_frame_tag @note.to_turbo_frame_id do %>
  <%= render 'form', note: @note %>
<% end %>

<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h2>My notes</h2>

<ul>
  <%= render @notes %>
  <%= turbo_frame_tag Note.new.to_turbo_frame_id, src: new_note_path, target: '_top' do %>
    Loading...
  <% end %>
</ul>

app/views/notes/new.html.erb
<h2>New note</h2>

<%= turbo_frame_tag @note.to_turbo_frame_id, target: '_top' do %>
  <%= render 'form', note: @note %>
<% end %>

<%= link_to 'Back', notes_path %>